# Generated by Django 5.1 on 2024-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_full_name_profile_id_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pos_officer',
            field=models.BooleanField(default=False),
        ),
    ]
