# Generated by Django 5.1 on 2024-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_pos_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
