# Generated by Django 5.1 on 2024-10-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(blank=True, choices=[('front_desk', 'front_desk'), ('pos_staff', 'pos_staff'), ('hr_staff', 'hr_ataff'), ('manager', 'manager'), ('waiter', 'waiter'), ('supervisor', 'supervisor'), ('potter', 'potter'), ('accountant', 'accountant'), ('store_keeper', 'store_keeper'), ('security', 'security')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='EmployeeRole',
        ),
    ]
