# Generated by Django 5.1 on 2024-09-18 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='staffonduty',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='staffschedules',
            name='schedule_changes',
        ),
        migrations.RemoveField(
            model_name='staffschedules',
            name='shift_coverage',
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('temporary', 'Temporary')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='schedule_shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('pos_shift', 'POS Shift'), ('hr_shift', 'HR Shift')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certification',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_department', to='hrm.department'),
        ),
        migrations.CreateModel(
            name='DepartmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='hrm.department')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='shift_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.departmentlocation'),
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pos_staff', 'POS Staff'), ('hr_staff', 'HR Staff'), ('manager', 'Manager')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrm.department')),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to='hrm.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeContract',
        ),
        migrations.DeleteModel(
            name='StaffOnDuty',
        ),
    ]
