# Generated by Django 5.1 on 2024-09-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_department_remove_staffonduty_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('24_hours', '24_hours'), ('Morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeerole',
            name='role',
            field=models.CharField(choices=[('front_desk', 'front_desk'), ('pos_staff', 'pos_staff'), ('hr_staff', 'hr_ataff'), ('manager', 'manager'), ('waiter', 'waiter'), ('supervisor', 'supervisor'), ('potter', 'potter'), ('accountant', 'accountant'), ('store_keeper', 'store_keeper'), ('security', 'security')], max_length=50),
        ),
        migrations.AlterField(
            model_name='staffschedules',
            name='schedule_shift_type',
            field=models.CharField(blank=True, choices=[('24_hours', '24_hours'), ('Morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffschedules',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('Pos_shift', 'Pos_shift'), ('Frontdesk_shift', 'Frontdesk_shift'), ('Potter_shift', 'Potter_shift'), ('Supervisor_shift', 'Supervisor_shift'), ('Waiter_shift', 'Waiter_shift'), ('Accountant_shift', 'Accountant_shift'), ('Store_keeper_shift', 'Store_keeper_shift'), ('Security_shift', 'Security_shift'), ('Hr_shift', 'hr_shift'), ('Manager', 'Manager')], max_length=50, null=True),
        ),
    ]
