# Generated by Django 5.1 on 2024-09-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_alter_attendance_shift_type_alter_employeerole_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
