# Generated by Django 5.1 on 2024-09-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_remove_employee_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedules',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='staffschedules',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
