# Generated by Django 5.1 on 2024-09-24 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_alter_staffschedules_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffschedules',
            old_name='schedule_date',
            new_name='schedule_end_date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffschedules',
            name='schedule_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staffschedules',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='staffschedules',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
