# Generated by Django 5.1 on 2024-09-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_rename_schedule_date_staffschedules_schedule_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedules',
            name='active',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False'), ('Ended', 'Ended')], default='False', max_length=20),
        ),
    ]
