# Generated by Django 5.1 on 2024-09-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_alter_staffschedules_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedules',
            name='active',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False'), ('Ended', 'Ended')], default='False', max_length=20),
        ),
    ]
