# Generated by Django 5.1 on 2024-09-25 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_alter_staffschedules_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_location',
        ),
        migrations.RemoveField(
            model_name='employeerole',
            name='department',
        ),
        migrations.AddField(
            model_name='employeerole',
            name='department_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='hrm.departmentlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'check_in')},
        ),
        migrations.AlterUniqueTogether(
            name='departmentlocation',
            unique_together={('department', 'name')},
        ),
    ]
