# Generated by Django 5.1 on 2024-10-08 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['id_code', 'name']},
        ),
        migrations.RenameField(
            model_name='amenity',
            old_name='display_order',
            new_name='id_code',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='amenity',
            name='reorder_level',
        ),
    ]
