# Generated by Django 5.1 on 2024-10-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
    ]
