# Generated by Django 5.1 on 2024-10-03 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alert_expiration_consumableitem_reorder_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='inventory.itemcategory')),
            ],
            options={
                'verbose_name_plural': 'blog_categories',
                'db_table': 'blog_categories',
                'unique_together': {('slug', 'parent')},
            },
        ),
    ]
