# Generated by Django 5.1 on 2024-10-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_employee_role_delete_employeerole'),
        ('inventory', '0002_alter_stockreceipt_department_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='for items being sold at POS', max_digits=12),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stocklog',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Incoming'), ('OUT', 'Outgoing'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return'), ('ADJUST', 'Adjustment')], max_length=10),
        ),
    ]
