# Generated by Django 5.1 on 2024-10-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement_performed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='selling_price_per_item',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='price_per_item',
            field=models.FloatField(default=0),
        ),
    ]
