# Generated by Django 5.1 on 2024-10-11 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_consumableitem_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumableitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumable', to='inventory.supplier'),
        ),
    ]
