# Generated by Django 5.1 on 2024-10-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_itemcategory_options_alter_itemcategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumableitem',
            name='purchase_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='cunsumable_receipts'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='equipment_receipts'),
        ),
    ]
