# Generated by Django 5.1 on 2024-10-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventorymovement_unit_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorymovement',
            name='unit_purchase_price',
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='unit_selling_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='For items being sold at POS', max_digits=12),
        ),
    ]
