# Generated by Django 5.1 on 2024-10-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_supplier_category_consumableitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumableitem',
            name='hotel',
        ),
    ]
