# Generated by Django 5.1 on 2024-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stockreceipt_product_sales_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreceipt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
