# Generated by Django 5.1 on 2024-10-04 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_consumableitem_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='hotel',
        ),
    ]
