# Generated by Django 5.1 on 2024-10-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_stockreceipt_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='unit_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='For items being sold at POS', max_digits=12, null=True),
        ),
    ]
