# Generated by Django 5.1 on 2024-10-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventorymovement_unit_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklog',
            name='unit_selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
