# Generated by Django 5.1 on 2024-09-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poscustomer',
            old_name='room_number',
            new_name='customer_room_number',
        ),
        migrations.AlterField(
            model_name='poscustomer',
            name='pos_customer',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
