# Generated by Django 5.1 on 2024-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='icon_class',
            field=models.CharField(choices=[('fa-bowl-rice', 'fa-bowl-rice'), ('fa-cocktail', 'fa-cocktail'), ('fa-ice-cream', 'fa-ice-cream'), ('fa-drumstick-bite', 'fa-drumstick-bite'), ('fa-hamburger', 'fa-hamburger')], default='fa-utensils', max_length=100),
        ),
    ]
