# Generated by Django 5.1 on 2024-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_rename_room_number_poscustomer_customer_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poscustomer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
