# Generated by Django 5.1 on 2024-09-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_product_icon_class_productcategory_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='pos.jpg', null=True, upload_to='pos'),
        ),
    ]
