# Generated by Django 5.1 on 2024-10-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_poscustomer_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosStockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField()),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('pos_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.posuser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
    ]
