# Generated by Django 5.1 on 2024-11-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roominventory',
            unique_together={('room', 'equipment', 'amenity')},
        ),
        migrations.RemoveField(
            model_name='roominventory',
            name='consumable',
        ),
    ]
