# Generated by Django 5.1 on 2024-08-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(blank=True, default='Live', max_length=10, null=True),
        ),
    ]
