# Generated by Django 5.1 on 2024-10-09 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('inventory', '0002_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.CreateModel(
            name='RoomInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('reserved', 'Reserved')], max_length=50)),
                ('consumable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.consumableitem')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.equipment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.room')),
            ],
            options={
                'unique_together': {('room', 'equipment', 'consumable')},
            },
        ),
        migrations.DeleteModel(
            name='RoomAmenity',
        ),
    ]
