# Generated by Django 5.1 on 2024-10-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_room_amenities_roominventory_and_more'),
        ('inventory', '0002_alter_amenity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roominventory',
            name='amenity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.amenity'),
        ),
    ]
