# Generated by Django 5.1 on 2024-11-23 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_roominventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.reservation'),
        ),
    ]
