# Generated by Django 5.1 on 2024-09-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(blank=True, choices=[('Delux', 'Delux'), ('Executive', 'Executive'), ('Presidential', 'Presidential')], max_length=20, null=True),
        ),
    ]
