# Generated by Django 5.1 on 2024-08-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_hotel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservices',
            name='service_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
