# Generated by Django 5.1 on 2024-10-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_room_remove_reservation_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusers',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='couponusers',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='additionalcharge',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalcharges', to='bookings.booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.room'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomservice', to='bookings.booking'),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
