# Generated by Django 5.1 on 2024-10-21 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusers',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='couponusers',
            name='mobile',
        ),
    ]
