# Generated by Django 5.1 on 2024-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_roomservices_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='room_type'),
        ),
    ]
