# Generated by Django 5.1 on 2024-08-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_roomtype_banner_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='banner_img',
            field=models.ImageField(blank=True, null=True, upload_to='rooms'),
        ),
    ]
