# Generated by Django 5.1 on 2024-10-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_roomservices_booking_delete_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcharge',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalcharges', to='bookings.booking'),
        ),
    ]
