# Generated by Django 5.1 on 2024-09-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_roomamenity_roomtype_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_from',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_type',
            field=models.CharField(choices=[('Advance', 'Advance'), ('Instant', 'Instant'), ('Groups', 'Groups'), ('Allocation', 'Allocation'), ('Business_Seminar', 'Business_Seminar'), ('Wedding', 'Wedding')], default='Instant', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'card'), ('transfer', 'transfer')], default='cash', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='vip',
            field=models.CharField(blank=True, default=False, max_length=200, null=True),
        ),
    ]
