# Generated by Django 5.1 on 2024-09-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_discount_amount_booking_discount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, null=True, to='bookings.coupon'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
