# Generated by Django 5.1 on 2024-09-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_alter_booking_coupons_alter_booking_vip'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('ground_floor', 'ground_floor'), ('first_floor', 'first_floor'), ('second_floor', 'second_floor')], default='ground_floor', max_length=20),
        ),
    ]
