# Generated by Django 5.1 on 2024-09-06 12:45

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_rename_advance_amount_booking_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomtype',
            old_name='price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='bookings.roomamenity'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(choices=[('ground_floor', 'Ground Floor'), ('first_floor', 'First Floor'), ('second_floor', 'Second Floor')], default='ground_floor', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('transaction_id', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='bookings.payment')),
            ],
        ),
    ]
