# Generated by Django 5.1 on 2024-09-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_rename_price_roomtype_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservices',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Food', 'Food'), ('Cleaning', 'Cleaning'), ('Technical', 'Technical')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(blank=True, choices=[('King', 'King'), ('Luxury', 'Luxury'), ('Normal', 'Normal'), ('Economic', 'Economic')], max_length=20, null=True),
        ),
    ]
