# Generated by Django 5.1 on 2024-09-10 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_alter_roomservices_service_type_alter_roomtype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomservices',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roomservice_set', to='bookings.booking'),
        ),
    ]
