# Generated by Django 5.1 on 2024-09-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_alter_roomservices_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='single_use',
            field=models.BooleanField(default=False),
        ),
    ]
