# Generated by Django 5.1 on 2024-09-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_paymentcompletion_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentcompletion',
            name='transaction_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
