# Generated by Django 5.1 on 2024-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('advance', 'Advance'), ('completed', 'Completed'), ('failed', 'Failed')], default='uncompleted', max_length=20)),
                ('source', models.CharField(choices=[('booking', 'Booking'), ('event', 'Event'), ('pos', 'POS')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
